blueprint:
  name: Aeotec WallMote7 Automation
  description: Configure actions for WallMote7
  domain: automation
  source_url: https://raw.githubusercontent.com/zpriddy/Home-Assistant-Blueprints/main/aeotec_wallmote_7.yaml
  author: Zachary Priddy
  input:
    wallmote_device:
      name: WallMote Device
      selector:
        device:
          filter:
            model: ZWA022
    dimming:
      name: Enable Dimming
      description: Enable dimming if the buttons are held down
      default: false
      selector:
        boolean:

    dimming_light:
      name: Dimmer Light
      description: Light to dim when held down.
      default:
      selector:
        entity:
          multiple: true
          filter:
            domain:
              - light
            supported_features:
              - light.LightEntityFeature.TRANSITION

    # Actions
    top_1:
      name: Actions for Top Pressed
      default:
      selector:
        action:

    top_2:
      name: Actions for Top Pressed 2x
      default:
      selector:
        action:
    top_3:
      name: Actions for Top Pressed 3x
      default:
      selector:
        action:

    top_4:
      name: Actions for Top Pressed 4x
      default:
      selector:
        action:

    top_5:
      name: Actions for Top Pressed 5x
      default:
      selector:
        action:

    top_held:
      name: Actions for Top Held
      description: This wont apply if dimming is enabled
      default:
      selector:
        action:

    bottom_1:
      name: Actions for Bottom Pressed
      default:
      selector:
        action:
    bottom_2:
      name: Actions for Bottom Pressed 2x
      default:
      selector:
        action:

    bottom_3:
      name: Actions for Bottom Pressed 3x
      default:
      selector:
        action:

    bottom_4:
      name: Actions for Bottom Pressed 4x
      default:
      selector:
        action:

    bottom_5:
      name: Actions for Bottom Pressed 5x
      default:
      selector:
        action:

    bottom_held:
      name: Actions for Bottom Held
      description: This wont apply if dimming is enabled
      default:
      selector:
        action:

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  # Top Button
  - platform: device
    device_id: !input wallmote_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "001"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 001
    value: 0
    id: Top1
  - platform: device
    device_id: !input wallmote_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "001"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 001
    value: 3
    id: Top2
  - platform: device
    device_id: !input wallmote_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "001"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 001
    value: 4
    id: Top3
  - platform: device
    device_id: !input wallmote_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "001"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 001
    value: 5
    id: Top4
  - platform: device
    device_id: !input wallmote_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "001"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 001
    value: 6
    id: Top5
  - platform: device
    device_id: !input wallmote_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "001"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 001
    value: 2
    id: TopHeld

  # Bottom Button
  - platform: device
    device_id: !input wallmote_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "002"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 002
    value: 0
    id: Bottom1
  - platform: device
    device_id: !input wallmote_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "002"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 002
    value: 3
    id: Bottom2
  - platform: device
    device_id: !input wallmote_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "002"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 002
    value: 4
    id: Bottom3
  - platform: device
    device_id: !input wallmote_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "002"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 002
    value: 5
    id: Bottom4
  - platform: device
    device_id: !input wallmote_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "002"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 002
    value: 6
    id: Bottom5
  - platform: device
    device_id: !input wallmote_device
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "002"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 002
    value: 2
    id: BottomHeld

  # Button Release Triggers
  - platform: device
    device_id: 1857a0a6e845e0539c062d2476aa2538
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "002"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 002
    value: 1
    id: Released
  - platform: device
    device_id: 1857a0a6e845e0539c062d2476aa2538
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "001"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 001
    value: 1
    id: Released

variables:
  dimmer_enabled: !input dimming

action:
  - choose:
      # Top Button
      - conditions:
          - condition: trigger
            id:
              - Top1
        sequence: !input top_1
      - conditions:
          - condition: trigger
            id:
              - Top2
        sequence: !input top_2
      - conditions:
          - condition: trigger
            id:
              - Top3
        sequence: !input top_3
      - conditions:
          - condition: trigger
            id:
              - Top4
        sequence: !input top_4
      - conditions:
          - condition: trigger
            id:
              - Top5
        sequence: !input top_5
      - conditions:
          - condition: trigger
            id:
              - TopHeld
          - condition: template
            value_template: "{{ dimmer_enabled == false}}"
        sequence: !input top_held

      # Top Dimmer
      - conditions:
          - condition: trigger
            id:
              - TopHeld
          - condition: template
            value_template: "{{ dimmer_enabled == true}}"
        sequence:
          - repeat:
            sequence:
              - service: light.turn_on
                target:
                  entity_id: !input dimming_light
                data:
                  brightness_step_pct: 10
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 0
                  milliseconds: 1
            until:
              - condition: numeric_state
                entity_id: !input dimming_light
                above: 99
                attribute: brightness

      # Bottom Button
      - conditions:
          - condition: trigger
            id:
              - Bottom1
        sequence: !input bottom_1
      - conditions:
          - condition: trigger
            id:
              - Bottom2
        sequence: !input bottom_2
      - conditions:
          - condition: trigger
            id:
              - Bottom3
        sequence: !input bottom_3
      - conditions:
          - condition: trigger
            id:
              - Bottom4
        sequence: !input bottom_4
      - conditions:
          - condition: trigger
            id:
              - Bottom5
        sequence: !input bottom_5
      - conditions:
          - condition: trigger
            id:
              - BottomHeld
          - condition: template
            value_template: "{{ dimmer_enabled == false}}"
        sequence: !input top_held

      # Bottom Dimmer
      - conditions:
          - condition: trigger
            id:
              - BottomHeld
          - condition: template
            value_template: "{{ dimmer_enabled == true}}"
        sequence:
          - repeat:
            sequence:
              - service: light.turn_on
                target:
                  entity_id: !input dimming_light
                data:
                  brightness_step_pct: -10
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 0
                  milliseconds: 1
            until:
              - condition: numeric_state
                entity_id: !input dimming_light
                below: 1
                attribute: brightness
